# Generated by Django 3.1 on 2021-01-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_taken_date',
            field=models.DateTimeField(null=True),
        ),
    ]
