# Generated by Django 3.1 on 2022-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220630_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='post_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
