# Generated by Django 3.1 on 2022-06-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
