# Generated by Django 3.1 on 2022-06-30 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date']},
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9_-]*$')]),
        ),
    ]
