# Generated by Django 3.1 on 2022-07-01 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220630_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_plate',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please only enter alphanumeric characters.', regex='^[A-Za-z0-9_-]*$')]),
        ),
    ]
