# Generated by Django 4.0.5 on 2022-07-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_car_number_plate_alter_donation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='customer',
        ),
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, help_text='House name / number & road', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='car',
            field=models.ForeignKey(default='feefa8ec-1461-41ec-aff7-b0ce2f4c9f5d', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='postal_town',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='postcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
