# Generated by Django 4.0.5 on 2022-07-17 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_donation_customer_donation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='car',
        ),
        migrations.AddField(
            model_name='donation',
            name='number_plate',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Please only enter alphanumeric characters.', regex='^[A-Za-z0-9 ]*$')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
